### ISSUE TITLE
檔名和資料編碼建議

### ISSUE THREAD

**Issue by siansiansu** [oliviakuo/TBN_VertebrateList#2]
檔名如果包含括弧和空白，程式會比較不好讀取，有需要更改嗎？

還有編碼如果不是 UTF-8，可能會有中文亂碼的情形喔~

**Comment by oliviakuo** [comment]
> 檔名如果包含括弧和空白，程式會比較不好讀取，有需要更改嗎？
> 
> 還有編碼如果不是 UTF-8，可能會有中文亂碼的情形喔~

感謝提供建議~~檔名部分已修改完成~
編碼的部分當初是因為考量有些物種的中文名如果以UTF-8編碼會變成問號ex.鴴，所以才決定上傳.xlsx檔。但是如果以bash或terminal開啟檔案的確會無法使用，因此目前新增一個資料夾"TBN_VertebrateList_UTF-8"內的檔案是以UTF-8編碼。
另外想請教一下，.xlsx檔是不是無法編碼或轉換編碼為UTF-8呢?因為以bash確認.xlsx檔編碼方式都顯示為binary且無法轉換為其他編碼方式。

**Comment by siansiansu** [comment]
正確來說，應該是使用 UTF-8 編碼之後才比較少問題 XD
Windows 的 Big5 編碼[太不友善了](https://www.ptt.cc/man/Web_Design/D5B9/D6D7/M.1144158540.A.A6E.html)。

如果要上傳到 GitHub 或其他平台，只傳 UTF-8 編碼會比較好
再傳一個 Big5 會有點麻煩，而且很少看到有人這麼做

至於組織內部該怎麼溝通和協作，可能要再討論一下

**Comment by oliviakuo** [comment]
好的，謝謝建議:))~~目前先將主要資料都替換為UTF-8 編碼的資料。
另外想請問，git本身已經具有版本控制的功能，那是不是在檔案命名上就不需要再有版本的命名呢?

**Comment by siansiansu** [comment]
不用~ git commit 的時候把訊息寫清楚就好了，不過如果擔心弄不見的話，就多備份一份XD

**Comment by oliviakuo** [comment]
> 不用~ git commit 的時候把訊息寫清楚就好了，不過如果擔心弄不見的話，就多備份一份XD

好哦~~~謝謝!!!^^
